FROM node:7.7-alpine

RUN mkdir -p /app
WORKDIR /app
COPY ./citation-practice-backend/package.json ./package.json
RUN npm install --quiet
COPY ./citation-practice-backend ./

CMD ["node", "src/index.js"]
